### ISSUE TITLE
Dealing with .C call 

### ISSUE THREAD

**Issue by william-denault** [stephenslab/fsusieR#7]
Hello @pcarbo ,

There is only two warnings left in the package. I don't really know how to deal with them.

The first problem
`W  checking dependencies in R code (2.4s)
   Objet non exporté importé par appel ':::' : 'stats:::C_cov'
     See the note in ?`:::` about the use of this operator.
     Including base/recommended package(s):
     'stats'`

To gain some speed I use the the actual  C call to compute the variance ( you can look in the `var` function of R the last line is a the following C call `.Call(C_cov, x, y, na.method, FALSE)` . This allow bypassing all the check of the var function and thus gainning some speed. However this seems to be somewhat problematic for the CRAN check

The second problem
`checking foreign function calls (2.4s)
   Foreign function call to a base package:
     .Call(stats:::C_cov, ...)
   Foreign function calls to a different package:
     .C("av_basisWRAP", ..., PACKAGE = "wavethresh")
     .C("comAB_WRAP", ..., PACKAGE = "wavethresh")
     .C("comwd", ..., PACKAGE = "wavethresh")
     .C("wavedecomp", ..., PACKAGE = "wavethresh")
   Packages should not make .C/.Call/.External/.Fortran calls to a base
   package. They are not part of the API, for use only by R itself and
   subject to change without notice.`

The second problem relates to making some Foreing call  of some fortran call from the wavethresh package. The code that generate this problem is from smashR. I  suspect that might be the reason why smashr is not on CRAN.

Do you have any idea on how to solve these problem without to much work?
My understanding is that the easiest is to copy (given that the licence is OK with it ) the necessay C code from the stat and the wavethresh packages and to include it susiF.alpha package

**Comment by pcarbo** [comment]
@william-denault This seems less important to fix right now, and might involve quite a bit of effort. I suggest leaving this issue as a reminder to fix it later.

**Comment by pcarbo** [comment]
@william-denault Shall we close this?

**Comment by william-denault** [comment]
fixed
