### ISSUE TITLE
Add variable and feature names to susiF output(s)

### ISSUE THREAD

**Issue by pcarbo** [stephenslab/fsusieR#8]
@william-denault It would be helpful to add "names" attributes to the susiF outputs (names, rownames, colnames, etc). These would be extracted from the X, Y inputs. You could start with "pip" for example. 

See `susieR` for some ideas, e.g.,

```
> X[1:4,1:4]
           v1         v2         v3         v4
s1 -0.5940634  1.1069687 -0.8742630  0.6955087
s2  0.1887028  1.0848210 -1.8791105  0.3561211
s3 -0.7961811 -0.8216644  1.5559896  1.2320516
s4  1.5527146  0.2182669  0.4887571 -0.7897537 
> res <- susie(X,y,verbose = FALSE)
> res$pip[1:4]
v1 v2 v3 v4
 1  1  1  1
> res$fitted[1:4]
        s1         s2         s3         s4
 0.2997196 -0.2348285  1.0807012  1.5738240
```

Do you see how the row/column names from X are carried over to the outputs?

**Comment by william-denault** [comment]
Hello @pcarbo ,

I agree I will update the package to make sure that the output inherit the columns names.


Best
W

**Comment by william-denault** [comment]
I have pushed an update that should fix most of what is needed.
let me know what you think about it.

**Comment by pcarbo** [comment]
@william-denault Looks good.
